-- またテーブル作る練習
-- テーブル制作
CREATE TABLE INFO2(
INFO_NO NUMBER CONSTRAINT pk PRIMARY KEY NOT NULL,
PC_NO VARCHAR2(10) UNIQUE NOT NULL,
NM VARCHAR2(10),
CAREER VARCHAR2(10),
HOBBY VARCHAR(1000)
);

INSERT INTO INFO2 (INFO_NO, PC_NO, NM, CAREER, HOBBY) VALUES(2106, 1004, '社員', 2, 'My hobby is Making computer');
INSERT INTO INFO2 (INFO_NO, PC_NO, NM, CAREER, HOBBY) VALUES(2110, 2001,'課長', 3, 'My hobby is Making collection');
INSERT INTO INFO2 (INFO_NO, PC_NO, NM, CAREER, HOBBY) VALUES(2101, 1005, '職人', 2, 'My hobby is swimming');
INSERT INTO INFO2 (INFO_NO, PC_NO, NM, CAREER, HOBBY) VALUES(2510, 1950, '部長', 3, 'My hobby is remake who is her goods');
INSERT INTO INFO2 (INFO_NO, PC_NO, NM, CAREER, HOBBY) VALUES(2104, 1521, '職人', 1, 'My hobby is swimming');



-- DATA選択
SELECT *
FROM INFO2;

SELECT
INFO_NO,
PC_NO,
CAREER
FROM INFO2;



-- DATA選択(+WHERE:条件)
SELECT *
FROM INFO2
WHERE PC_NO > 1500;
ORDER BY INFO_NO ASC;

SELECT *
FROM INFO2
WHERE PC_NO > 1500
AND NM = '職人';



-- UPDATE DATA SELECTED
UPDATE INFO
SET HOBBY = 'Work'
WHERE NM = '職人';



-- DELETE
DELETE INFO
WHERE NM = '職人';
-- ALL DELETE
DELETE INFO;
