-- dep, emp　リレイション形式にテーブルを制作
CREATE TABLE dep (
deptno NUMBER(3) CONSTRAINT dep_pk_deptno PRIMARY KEY,
depname VARCHAR(20),
floor NUMBER(5)
);

CREATE TABLE emp(
empno NUMBER(5) CONSTRAINT emp_pk_employee PRIMARY KEY,
empname VARCHAR2(20),
title VARCHAR2(20),
dno NUMBER(3) CONSTRAINT emp_fk_dno REFERENCES dep(deptno),
salary NUMBER(10)
);


-- insert data
INSERT INTO DEP (DEPTNO, DEPNAME, FLOOR) VALUES(1, '営業', 8);
INSERT INTO DEP (DEPTNO, DEPNAME, FLOOR) VALUES(2, '企画', 10);
INSERT INTO DEP (DEPTNO, DEPNAME, FLOOR) VALUES(3, '開発', 9);

INSERT INTO EMP (EMPNO, EMPNAME, TITLE, DNO, SALARY) VALUES(2106, '坂本', '社長', 2, 20005234);
INSERT INTO EMP (EMPNO, EMPNAME, TITLE, DNO, SALARY) VALUES(2110, '宮本', '課長', 3, 20044153);
INSERT INTO EMP (EMPNO, EMPNAME, TITLE, DNO, SALARY) VALUES(2101, '中野', '社員', 2, 20005223);
INSERT INTO EMP (EMPNO, EMPNAME, TITLE, DNO, SALARY) VALUES(2510, '故郷', '部長', 3, 25663203);
INSERT INTO EMP (EMPNO, EMPNAME, TITLE, DNO, SALARY) VALUES(2104, '岩井', '社員', 1, 20234123);


-- display data
SELECT
        DEP.DEPNAME AS ROOM,
        DEP.FLOOR || 'FLOOR' AS LOCATION,
        EMP.EMPNAME AS HUMAN_NAME,
        EMP.TITLE AS CLASS,
        EMP.SALARY || 'YEN' AS PAY,
        TO_CHAR( EMP.SALARY * 12, '999,999,999,999,999') AS "1YEAR_PAY"
FROM DEP, EMP
WHERE DEP.DEPTNO = EMP. DNO
ORDER BY SALARY DESC ;


-- REMOVE
DROP TABLE dep CASCADE CONSTRAINT;
DROP TABLE emp;


-- 데이터 삭제
DROP TABLE DEP;
DROP TABLE EMP;

-- 제약조건까지 REMOVE
DROP TABLE dep CASCADE CONSTRAINT;